### ISSUE TITLE
Segment3DImage throws a NullPointerException

### ISSUE THREAD

**Issue by rensutheart** [mcib3d/mcib3d-core#19]
Hi,

I'm busy writing a Plugin for ImageJ/Fiji and I'm trying to 3D segment some biological structures in a z-stack in Java. The Segment3DImage class looks like it is exactly what I need. However, I did notice that it was marked as Deprecated about 2 months ago. Is there an alternative that you would suggest? I'm still using version 3.96.3 however.

Currently when I try to use it, as soon as I call `getLabelledObjectsImage3D()` I get a null pointer exception.

The Code I use (after loading my image as an ImagePlus)
```java
        Segment3DImage segment3D = new Segment3DImage(imagePlus, 0, 500f);
        ImageInt outputSeg3D = segment3D.getLabelledObjectsImage3D();
```
The error log:
```
java.lang.NullPointerException
	at mcib3d.image3d.Segment3DImage.buildImg(Segment3DImage.java:481)
	at mcib3d.image3d.Segment3DImage.getLabelledObjectsImage3D(Segment3DImage.java:305)
```

The image that I try to segment. Note that I've also tried non-thresholded images.
[Frame1_Thresholded.zip](https://github.com/mcib3d/mcib3d-core/files/6175079/Frame1_Thresholded.zip)

**Comment by rensutheart** [comment]
For someone else looking into this. My workaround was to instead use 3D Object Counter.

```java
// Assuming there is an image already open with the name stored in title_Frame1
ImagePlus imagePlus_Frame1 = WindowManager.getImage(title_Frame1);
IJ.run(imagePlus_Frame1, "3D Objects Counter", "threshold=50 slice=1 min.=10 max.=1048576 objects");
Img<UnsignedIntType> labeledImage = ImageJFunctions.wrap(WindowManager.getImage("Objects map of " + title_Frame1));
```

**Comment by mcib3d** [comment]
The class Segment3DImage is taken directly from the 3DObjectsCounter plugin; it is quite time-consuming. We wrote a more efficient algorithm available in the class **ImageLabeller** that will take an already thresholded image as input and return its connected components labels : 
`
// create the labeller
ImageLabeller labeler = new ImageLabeller();
// you can add min and max size for the connected components
 labeler.setMinSize(min);
 labeler.setMaxsize(max);
// get the labelled image
ImageHandler res = labeler.getLabels(bin);
`
In order to threshold the image, use the methods available in ImageHandler : 
`
ImageHandler img = ImageHandler.wrap(myPlus);
ImageInt bin = img.thresholdAboveInclusive(low);
`
Best

Thomas

**Comment by rensutheart** [comment]
Hi Thomas,

Thank you for the reply! It is quite helpful! I will have a look at it!
